name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 11

      - name: Make setup - install dependencies
        run: make setup

      - name: Make lint - run linter
        run: make lint

      - name: Make test - run tests
        run: make test
